## spring
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: flyway
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration/schema
    url: jdbc:mysql://localhost:3306/hot6
    schemas: test
    user: root
    password: benx0508!
