## spring
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: flyway
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration/schema
    url: jdbc:mysql://localhost:3306/tdsn
    user: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
