# default profile
spring:
  profiles:
    include:
      - httpclient
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # kakao login
  security:
    front-redirect-uri: /login/kakaoauth
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(XGWtqHAq/Kl2l0YnKe5pUfd9VbsbLwMnSK/fMBfS/RDGGGPMRxZuP7N2g9kBLR1xpZ9zmwqsvjm4Z9YVm3s4KlYUyN4pPrd6tk7UxhHdMQ0=)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # swagger issue
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: ENC(BF9EmOQPpQJ8n8uZwUgw37wHFDBQg9wCNHiZUcDnNTbQbHwUd//RIfjiCO38GavO7PIuCKm11FFVhKG1HofyiljZBCCD83eOzw9lWZi6VXE=)

server:
  port: 8080
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8
  forward-headers-strategy: framework

# AWS Setting
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(6idhGUehK+L1MtXUCONoZMpozvTEt0b5cK6a8PDaBOlBegaWCIxcr28jh7NCbHRtQtUYTTwIPYVfGa8KTfYjFQ==)
      secret-key: ENC(6tPbHY36pQo7x7dF1v80xRcajQoQU81d/tgDbxECK5whJohWjCCj19QIuA5lIdE5kzgINGpbtiwo4k+4Qlesj0LzKlcRdGeBTyey1AjQl/8=)

    s3:
      bucket: ENC(LZJ5s+QVjQfyf7KQb+bTMwbd+CN2Ji9j4ipsVleNo0b7hYBdTGN6nINAFtvXQLwhIk1RfjI+d8MlbyTLMyJ+CQ==)
      upload:
        path.review: public/review
      cdn:
        url: https://tdns.s3.ap-northeast-2.amazonaws.com

# security
security:
  permit-url: /api-docs/**,/configuration/**,/swagger-ui/**,/webjars/**,/actuator/health,/swagger/**,/swagger/index.html,/login/**,/api/v1/user/renew
  filter-skip: /actuator/health,/api-docs,/configuration,/swagger,/swagger-ui,/webjars,/swagger/**,/api/v1/user/renew,/login

# swagger
springdoc:
  version: '1.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**
