spring:
  datasource:
    url: ENC(en7/4fExjy595I898lm8B3ctoWtvIZoGVdcMoSctjBGBn2LmTuG9588zCrKzjvwK/B9704N3NmJL05W/BEutO5tkQffoybsHmJghWwTiZ0y4FsQSwY9oBQ6+3edZrkTip9xtxlnkDfs6p8FmDTfWRBYxQPcAnJuHKHePGmh9d8E=)
    username: ENC(XZgCSKYBjOGxjU5koULVISqUMWSqaLygaIJwHEXq9ZyI2S0AQmvE97XuakgjFPMv)
    password: ENC(17+mE7X+dMMjiJu+7CuwVp2bhhwKCw85SJpBGMBAgL0STOUgszKa7Yozd1FYeCPn)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  security:
    oauth2:
      localhost: http://localhost:3000
      client:
        registration:
          kakao:
            redirect-uri: https://api.tokstudy.com/login/oauth2/code/kakao
  devtools:
    restart:
      enabled: false
  redis:
    host: ENC(P17UqLHtbnPOcrTHSNcDYUMQQU6t650oGfGqDpEUnfOvjdagKLgniJMEQrPChh38Y97a7SYAVyTaSWpN/QoVNbiWVAJ4lORPTzIvMEUsHb43wYPnUj7+u0IxDP9HCkvX1jTuLrpebTfPKm4ILF/oiA==)
    port: 6379
url:
  prefix: <dev url>
  study-path: /study
  join-path: /join
