spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  security:
    oauth2:
      localhost: http://localhost:3000
      client:
        registration:
          kakao:
            redirect-uri: https://tokstudy.com/login/oauth2/code/kakao
  redis:
    host:
    port:
url:
  prefix: <prod url>
  study-path: /study
  join-path: /join
